create:
	@python -m venv CO2

act:
	@powershell -ExecutionPolicy Bypass -File ./CO2/Scripts/Activate.ps1

start:
	@uvicorn app.main:app --reload

run:
	@python main.py

test:
	@pytest -v app/

freeze:
	@.\CO2\Scripts\python.exe -m pip freeze > requirements.txt

install:
	@CO2/Scripts/pip install -r requirements.txt
	@CO2/Scripts/python.exe -m pip install --upgrade pip

delete:
	@rmdir /s /q venv

generate:
	@python config/keys.py